import {launchBrowser} from './browser.mjs';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.ORBIT_URL||'http://127.0.0.1:5516/',out=process.env.ORBIT_EVIDENCE||'evidence/final-extra',records=[];await mkdir(out,{recursive:true});const browser=await launchBrowser();
try {
for(const [name,width,height,lang,enlarged] of [['small-ru',320,568,'ru',false],['small-kk',320,568,'kk',false],['small-landscape',568,320,'en',false],['text-200-kk',320,568,'kk',true]]){
 const context=await browser.newContext({viewport:{width,height}}),page=await context.newPage();await page.goto(`${base}?lang=${lang}`);await page.waitForFunction(()=>window.__ORBIT);await page.evaluate(()=>document.fonts.ready);if(enlarged){await page.addStyleTag({content:'html{font-size:200%}'});await page.waitForFunction(()=>document.documentElement.classList.contains('text-enlarged'));}
 for(const summary of await page.locator('.help summary').all()){await summary.scrollIntoViewIfNeeded();await summary.click();await page.waitForTimeout(80);const r=await summary.locator('..').locator('p').boundingBox();assert.ok(r.x>=15&&r.x+r.width<=width-15,`${name}: tooltip clipping ${JSON.stringify(r)}`);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name);await summary.click();}
 await page.locator('#mission-name').fill('One');await page.locator('#save').click();await page.locator('#inclination').fill('180');await page.locator('#mission-name').fill('Two');await page.locator('#save').click();await page.locator('[data-compare="0"]').click();await page.locator('[data-compare="1"]').click();await page.locator('#comparison').scrollIntoViewIfNeeded();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${name}: comparison overflow`);await page.screenshot({path:`${out}/${name}-compare.png`});
 const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();assert.deepEqual(axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);await page.locator('#assembly').fill('100');await page.locator('#assembly-scene').scrollIntoViewIfNeeded();await page.waitForTimeout(100);const s=await page.evaluate(()=>window.__ORBIT.state()),b=s.assembly.bounds;assert.ok(b.left>=1&&b.right<=s.assembly.width-1&&b.top>=1&&b.bottom<=s.assembly.height-1);await page.screenshot({path:`${out}/${name}-assembly.png`});await context.close();records.push({name,width,height,lang,enlarged,passed:true});console.log(`${name}: tooltips, compare, assembly and accessibility passed`);
}
// Both WebGL contexts restore; a folded panel change made during loss renders on recovery.
const page=await browser.newPage({viewport:{width:1280,height:800}});await page.goto(base);await page.waitForFunction(()=>window.__ORBIT);await page.locator('#assembly').fill('70');await page.locator('#assembly-scene').scrollIntoViewIfNeeded();await page.waitForTimeout(150);await page.evaluate(()=>{window.__loss=document.querySelector('#assembly-scene canvas').getContext('webgl2').getExtension('WEBGL_lose_context');window.__loss.loseContext();});await page.waitForFunction(()=>window.__ORBIT.state().assembly.lost);await page.locator('#assembly').fill('100');await page.waitForTimeout(150);await page.evaluate(()=>window.__loss.restoreContext());await page.waitForFunction(()=>window.__ORBIT.state().assembly.webgl);await page.waitForFunction(()=>window.__ORBIT.state().assembly.explosion===1);await page.screenshot({path:`${out}/assembly-context-recovered.png`});await page.close();records.push({name:'assembly-context-recovery',passed:true});
await writeFile(`${out}/report.json`,JSON.stringify(records,null,2));console.log('PASS: extra audit');
}finally{await browser.close();}
