import {launchBrowser} from './browser.mjs';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.ORBIT_URL||'http://127.0.0.1:5515/',out=process.env.ORBIT_EVIDENCE||'evidence/round-2',group=process.env.ORBIT_GROUP;await mkdir(out,{recursive:true});
const browser=await launchBrowser(),records=[];
const state=page=>page.evaluate(()=>window.__ORBIT.state());
async function ready(page,url=base){await page.goto(url);await page.waitForFunction(()=>window.__ORBIT);await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(150);}
async function jump(page,p){await page.evaluate(p=>{const s=window.__ORBIT.state();scrollTo({top:s.scroll.start+s.scroll.range*p,behavior:'instant'});},p);await page.waitForTimeout(130);}
async function noOverflow(page,label){assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${label}: horizontal overflow`);}
async function bounds(page,which,label){const s=(await state(page))[which],b=s.bounds;assert.ok(b.left>=1&&b.top>=1&&b.right<=s.width-1&&b.bottom<=s.height-1,`${label}: clipping ${JSON.stringify(b)} in ${s.width}×${s.height}`);}
async function axe(page,label){const r=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();const violations=r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}));assert.deepEqual(violations,[],`${label}: accessibility`);}
async function save(page,name){await page.locator('#mission-name').fill(name);await page.locator('#save').click();}
try {
if(!group||group==='regular')for(const [name,width,height,lang] of [['desktop',1440,1000,'en'],['laptop',1280,800,'ru'],['tablet',768,1024,'kk'],['mobile',390,844,'en'],['small',320,568,'en'],['mobile-ru',390,844,'ru'],['mobile-kk',390,844,'kk'],['landscape',844,390,'en']]){
 const context=await browser.newContext({viewport:{width,height},hasTouch:width<600}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await ready(page,`${base}?lang=${lang}`);assert.equal((await state(page)).scene.webgl,true);
 await page.screenshot({path:`${out}/${name}-spacecraft.png`});await page.locator('#scene').scrollIntoViewIfNeeded();await page.waitForTimeout(100);await bounds(page,'scene',name);await page.locator('#scene').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowUp');await page.waitForTimeout(100);await bounds(page,'scene',`${name}: rotated`);await page.keyboard.press('Home');
 await page.locator('#deploy').click();await page.waitForFunction(()=>window.__ORBIT.state().scene.deployment<.001);assert.equal((await state(page)).archive.current.deployed,false);await page.locator('#deploy').click();await page.waitForFunction(()=>window.__ORBIT.state().scene.deployment===1);
 await page.locator('[data-preset="2"]').click();assert.equal((await state(page)).archive.current.inclination,90);await page.locator('#orbit-tab').click();await page.waitForTimeout(150);await bounds(page,'scene',`${name}: polar orbit`);await page.screenshot({path:`${out}/${name}-orbit.png`});await page.locator('#play').click();assert.equal((await state(page)).playing,false);const paused=(await state(page)).seconds;await page.waitForTimeout(150);assert.equal((await state(page)).seconds,paused);await page.locator('#speed').selectOption('300');assert.ok((await page.locator('[data-i18n="motionNote"]').textContent()).includes('300'));await page.locator('#phase').fill('90');await page.locator('#restart').click();await page.waitForTimeout(50);assert.equal((await state(page)).seconds,0);await page.locator('#play').click();
 await page.locator('#altitude').fill('2000');await page.locator('#altitude').dispatchEvent('change');await page.locator('#inclination').fill('120');await page.locator('#inclination').dispatchEvent('change');assert.equal((await state(page)).archive.current.altitude,2000);assert.equal(await page.locator('#latitude').textContent(),'±60');await page.locator('#scene').scrollIntoViewIfNeeded();await page.waitForTimeout(100);await bounds(page,'scene',`${name}: maximum-altitude orbit`);await page.locator('#reset').click();
 const steps=[];for(const p of [0,.2,.5,.8,1,.8,.5,.2,0]){await jump(page,p);const s=await state(page);assert.ok(Math.abs(s.progress-p)<.006,`${name} scroll ${p}: ${s.progress}`);await bounds(page,'assembly',`${name} assembly ${p}`);await noOverflow(page,name);steps.push({p,calls:s.assembly.calls,triangles:s.assembly.triangles,bounds:s.assembly.bounds});if([.5,1].includes(p))await page.screenshot({path:`${out}/${name}-assembly-${p}.png`});}
 await page.locator('[data-chapter="3"]').click();assert.equal((await state(page)).manual,true);await page.locator('#assembly').fill('100');assert.equal((await state(page)).progress,1);await page.locator('#follow').click();assert.equal((await state(page)).manual,false);
 await save(page,'Explorer');await page.locator('[data-preset="2"]').click();await save(page,'Polar');assert.equal((await state(page)).archive.missions.length,2);await page.locator('[data-compare="0"]').click();await page.locator('[data-compare="1"]').click();assert.equal(await page.locator('tbody tr').count(),8);assert.ok(await page.locator('tr.different').count()>=4);await page.screenshot({path:`${out}/${name}-library.png`});await noOverflow(page,name);await axe(page,name);
 await page.locator('[data-load="0"]').click();assert.equal((await state(page)).archive.current.altitude,550);await page.reload();await page.waitForFunction(()=>window.__ORBIT?.state().archive.missions.length===2);assert.equal((await state(page)).archive.current.altitude,550);assert.deepEqual(errors,[]);records.push({name,width,height,lang,steps,errors,axeViolations:0});console.log(`${name}: full workflow passed`);await context.close();
}
// Interrupted/repeated actions, stale asynchronous reads, name safety and capacity.
if(!group||group==='edge'){
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});await context.addInitScript(()=>{const original=File.prototype.text;File.prototype.text=async function(){if(this.name==='slow.json')await new Promise(resolve=>setTimeout(resolve,450));return original.call(this);};});const page=await context.newPage();await ready(page);
 const special='<img src=x onerror=alert(1)>';await save(page,special);await save(page,special);assert.equal(await page.locator('#dialog').evaluate(d=>d.open),true);await page.keyboard.press('Escape');assert.equal((await state(page)).archive.missions.length,1);assert.equal(await page.locator('.saved-details img').count(),0);await save(page,special);await page.locator('[data-action="confirm"]').click();assert.equal((await state(page)).archive.missions.length,1);
 const current=(await state(page)).archive.current,before=(await state(page)).archive;
 for(const raw of ['{',JSON.stringify({version:1,current:{...current,altitude:99999},missions:[]}),JSON.stringify({version:1,current,missions:[{name:'A',mission:current},{name:'a',mission:current}]})]){await page.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(raw)});await page.waitForTimeout(100);assert.equal(await page.locator('#dialog').evaluate(d=>d.open),false);assert.deepEqual((await state(page)).archive,before);}
 const imported={version:1,current:{...current,altitude:800},missions:[{name:'Imported',mission:{...current,altitude:800}}]};
 const file=(name,body)=>({name,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(body))});
 await page.locator('#import-file').setInputFiles(file('slow.json',{...imported,missions:[{name:'Stale',mission:current}]}));await page.locator('#import-file').setInputFiles(file('valid.json',imported));await page.waitForFunction(()=>document.querySelector('#dialog').open);await page.waitForTimeout(500);assert.ok(!(await page.locator('#dialog-content').textContent()).includes('Stale'));await page.keyboard.press('Escape');assert.deepEqual((await state(page)).archive,before);
 await page.locator('#import-file').setInputFiles(file('valid.json',imported));await page.locator('[data-action="merge"]').click();assert.equal((await state(page)).archive.missions.length,2);assert.equal((await state(page)).archive.current.altitude,550);await page.locator('#undo').click();assert.equal((await state(page)).archive.missions.length,1);
 await page.locator('#import-file').setInputFiles(file('valid.json',imported));await page.locator('[data-action="replaceAll"]').click();assert.equal((await state(page)).archive.current.altitude,800);await page.locator('#undo').click();assert.deepEqual((await state(page)).archive,before);
 await page.locator('[data-delete="0"]').click();await page.keyboard.press('Escape');assert.equal((await state(page)).archive.missions.length,1);await page.locator('[data-delete="0"]').click();await page.locator('[data-action="confirm"]').click();assert.equal((await state(page)).archive.missions.length,0);await page.locator('#undo').click();assert.equal((await state(page)).archive.missions.length,1);
 for(let i=1;i<8;i++)await save(page,`Mission ${i}`);await save(page,'Capacity');assert.equal((await state(page)).archive.missions.length,8);assert.equal(await page.locator('#dialog').evaluate(d=>d.open),false);
 const event=page.waitForEvent('download');await page.locator('#export').click();const d=await event;await d.saveAs(`${out}/export.json`);assert.equal(d.suggestedFilename(),'orbit-missions.json');
 for(const l of ['ru','kk','en']){await page.locator(`[data-lang="${l}"]`).click();assert.equal((await state(page)).locale,l);assert.equal((await state(page)).archive.missions.length,8);}
 await jump(page,.55);await page.locator('#assembly').fill('55');for(const [width,height] of [[844,390],[390,844]]){await page.setViewportSize({width,height});await page.locator('#assembly-scene').scrollIntoViewIfNeeded();await page.waitForTimeout(200);assert.equal((await state(page)).progress,.55);await bounds(page,'assembly','orientation');await noOverflow(page,'orientation');}await page.screenshot({path:`${out}/orientation.png`});
 // Native touch scroll on the interactive 3D host must still move the page.
 await page.locator('#scene').scrollIntoViewIfNeeded();const rect=await page.locator('#scene').boundingBox(),y=await page.evaluate(()=>scrollY),cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:rect.x+rect.width/2,y:rect.y+rect.height*.75}]});for(let i=1;i<=6;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:rect.x+rect.width/2,y:rect.y+rect.height*.75-i*20}]});}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(200);assert.ok(await page.evaluate(y=>scrollY>y+30,y));await cdp.detach();await context.close();records.push({name:'interruption-repeat-touch-orientation',passed:true});console.log('Interrupted/repeated actions, validation, orientation and touch: passed');
}
for(const mode of ['fallback','reduced','blocked','corrupt','text-200'].filter(mode=>!group||group==='failure'||group===mode)){
 const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:mode==='reduced'?'reduce':'no-preference'});
 if(mode==='fallback')await context.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type.startsWith('webgl'))return null;return original.call(this,type,...args);};});
 if(mode==='blocked')await context.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('blocked','QuotaExceededError');};});
 if(mode==='corrupt')await context.addInitScript(()=>{localStorage.setItem('orbit-studio-v1','{unreadable');});
 const page=await context.newPage();await ready(page,`${base}?lang=ru`);
 if(mode==='fallback'){assert.equal((await state(page)).scene.webgl,false);await page.locator('#orbit-tab').click();await page.locator('#phase').fill('90');assert.equal(await page.locator('#scene .diagram svg').count(),1);}
 if(mode==='reduced'){assert.equal((await state(page)).playing,false);await page.locator('#deploy').click();await page.waitForFunction(()=>window.__ORBIT.state().scene.deployment===0);await jump(page,.8);await page.locator('#assembly').fill('100');await page.waitForFunction(()=>window.__ORBIT.state().assembly.explosion===1);}
 if(mode==='text-200'){await page.addStyleTag({content:'html{font-size:200%}'});await page.waitForFunction(()=>document.documentElement.classList.contains('text-enlarged'));await page.locator('#assembly').fill('100');await page.locator('#assembly-scene').scrollIntoViewIfNeeded();await page.waitForTimeout(150);await bounds(page,'assembly',mode);await noOverflow(page,mode);}
 await save(page,'Safe session');assert.equal((await state(page)).archive.missions.length,1);
 if(mode==='blocked')assert.equal((await state(page)).storageUnavailable,true);
 if(mode==='corrupt'){assert.equal(await page.evaluate(()=>localStorage.getItem('orbit-studio-v1')),'{unreadable');await page.locator('#replace-storage').click();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>localStorage.getItem('orbit-studio-v1')),'{unreadable');await page.locator('#replace-storage').click();await page.locator('[data-action="confirm"]').click();assert.equal((await state(page)).unreadable,false);assert.equal(JSON.parse(await page.evaluate(()=>localStorage.getItem('orbit-studio-v1'))).missions.length,1);}
 await noOverflow(page,mode);await axe(page,mode);await page.screenshot({path:`${out}/${mode}.png`,fullPage:mode==='text-200'});await context.close();records.push({name:mode,passed:true});console.log(`${mode}: passed`);
}
if(!group||group==='recovery'){
 const context=await browser.newContext({viewport:{width:1280,height:800}}),page=await context.newPage();await ready(page);await page.locator('#orbit-tab').click();await save(page,'Recoverable');await page.locator('#scene').scrollIntoViewIfNeeded();await page.evaluate(()=>{window.__loss=document.querySelector('#scene canvas').getContext('webgl2').getExtension('WEBGL_lose_context');window.__loss.loseContext();});await page.waitForFunction(()=>window.__ORBIT.state().scene.lost);assert.equal((await state(page)).archive.missions.length,1);await page.locator('#inclination').fill('90');await page.waitForTimeout(200);await page.evaluate(()=>window.__loss.restoreContext());await page.waitForFunction(()=>window.__ORBIT.state().scene.webgl);await page.waitForTimeout(150);assert.equal((await state(page)).archive.current.inclination,90);await page.screenshot({path:`${out}/context-recovered.png`});
 await page.locator('#play').click();const a=(await state(page)).scene.renders;await page.waitForTimeout(250);assert.equal((await state(page)).scene.renders,a,'Paused scene should not render continuously');await page.locator('#library').scrollIntoViewIfNeeded();await page.waitForTimeout(200);const off=await state(page);await page.waitForTimeout(250);const after=await state(page);assert.equal(after.scene.renders,off.scene.renders);assert.equal(after.assembly.renders,off.assembly.renders);await context.close();records.push({name:'context-recovery-and-render-cost',passed:true});console.log('Context recovery, pause and offscreen rendering: passed');
}
if(!group||group==='tabs'){
 const context=await browser.newContext(),a=await context.newPage(),b=await context.newPage();await ready(a);await ready(b);await save(a,'Tab A');await b.waitForFunction(()=>window.__ORBIT.state().conflict);await save(b,'Tab B');assert.equal((await state(b)).archive.missions[0].name,'Tab B');assert.equal(JSON.parse(await a.evaluate(()=>localStorage.getItem('orbit-studio-v1'))).missions[0].name,'Tab A');await context.close();records.push({name:'multiple-tab-data-protection',passed:true});console.log('Multiple-tab data protection: passed');
}
await writeFile(`${out}/report.json`,JSON.stringify({base,browser:'Headless installed Google Chrome on Windows; emulated viewports and touch',records},null,2));console.log(`PASS: ${records.length} audit scenarios`);
}catch(error){await writeFile(`${out}/failure.txt`,String(error.stack));throw error;}finally{await browser.close();}
