import {chromium} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const out='evidence/motion',base=process.env.ORBIT_URL||'http://127.0.0.1:5515/';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}:{})}),page=await browser.newPage({viewport:{width:1440,height:1080}});await page.goto(base);await page.waitForFunction(()=>window.__ORBIT);await page.evaluate(()=>document.fonts.ready);
async function start(selector){await page.evaluate(selector=>{const canvas=document.querySelector(selector);const stream=canvas.captureStream(24),chunks=[];window.__recorded=null;window.__recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp9',videoBitsPerSecond:1600000});window.__recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};window.__recorder.onstop=async()=>{const blob=new Blob(chunks,{type:'video/webm'}),buffer=await blob.arrayBuffer();let str='';for(const b of new Uint8Array(buffer))str+=String.fromCharCode(b);window.__recorded=btoa(str);stream.getTracks().forEach(t=>t.stop());};window.__recorder.start();},selector);}
async function finish(name){await page.evaluate(()=>window.__recorder.stop());await page.waitForFunction(()=>window.__recorded);await writeFile(`${out}/${name}.webm`,Buffer.from(await page.evaluate(()=>window.__recorded),'base64'));console.log(`Saved ${name}.webm`);}
await page.locator('#orbit-tab').click();await page.locator('#scene').scrollIntoViewIfNeeded();await page.locator('#speed').selectOption('300');await start('#scene canvas');await page.waitForTimeout(8000);await finish('circular-orbit-300x');
await page.locator('#sat-tab').click();await start('#scene canvas');await page.locator('#deploy').click();await page.waitForTimeout(2500);await page.locator('#deploy').click();await page.waitForTimeout(2500);await finish('solar-wing-deployment');
await page.evaluate(()=>{const s=window.__ORBIT.state();scrollTo({top:s.scroll.start+s.scroll.range*.1,behavior:'instant'});});await page.waitForTimeout(200);await start('#assembly-scene canvas');await page.evaluate(async()=>{const s=window.__ORBIT.state();for(const [from,to] of [[.1,1],[1,.1]]){const start=performance.now();await new Promise(resolve=>{function frame(now){const f=Math.min(1,(now-start)/3500),ease=f*f*(3-2*f);scrollTo({top:s.scroll.start+s.scroll.range*(from+(to-from)*ease),behavior:'instant'});if(f<1)requestAnimationFrame(frame);else resolve();}requestAnimationFrame(frame);});}});await finish('assembly-forward-and-reverse');await browser.close();
