import {launchBrowser} from './browser.mjs';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const root=process.env.ORBIT_MOTION||'evidence/motion';await mkdir(`${root}/review`,{recursive:true});const browser=await launchBrowser(),page=await browser.newPage({viewport:{width:1440,height:1200}}),records=[];
try{for(const name of ['circular-orbit-300x','solar-wing-deployment','assembly-forward-and-reverse']){
 const data=await readFile(`${root}/${name}.webm`);await page.setContent('<body style="margin:0;background:#121018"><video muted style="width:100%;height:100vh;object-fit:contain"></video></body>');
 await page.locator('video').evaluate(async(video,base64)=>{const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0));video.src=URL.createObjectURL(new Blob([bytes],{type:'video/webm'}));await new Promise(resolve=>video.addEventListener('loadedmetadata',resolve,{once:true}));video.currentTime=10000;await new Promise(resolve=>video.addEventListener('seeked',resolve,{once:true}));},data.toString('base64'));
 const metadata=await page.locator('video').evaluate(v=>({duration:v.duration,width:v.videoWidth,height:v.videoHeight}));assert.ok(Number.isFinite(metadata.duration)&&metadata.duration>3);const cells=[],hashes=[];
 for(const fraction of [.05,.2,.35,.5,.65,.8,.95]){await page.locator('video').evaluate(async(v,f)=>{v.currentTime=v.duration*f;await new Promise(resolve=>v.addEventListener('seeked',resolve,{once:true}));},fraction);const shot=await page.screenshot({path:`${root}/review/${name}-${fraction}.png`});hashes.push(shot.toString('base64').slice(-300));cells.push(`<figure><img src="data:image/png;base64,${shot.toString('base64')}"><figcaption>${(metadata.duration*fraction).toFixed(2)} s</figcaption></figure>`);}
 assert.ok(new Set(hashes).size>=3,`${name}: no recorded motion`);await page.setContent(`<body style="margin:0;padding:20px;background:#121018;color:#eee;font:16px Arial;display:grid;grid-template-columns:repeat(3,1fr);gap:15px">${cells.join('')}<style>figure{margin:0;background:#201b2c}img{width:100%;height:300px;object-fit:contain}figcaption{padding:10px}</style></body>`);await page.screenshot({path:`${root}/review/${name}-contact.png`,fullPage:true});records.push({name,...metadata,sampledFrames:7,moving:true});console.log(name,metadata);
}await writeFile(`${root}/review/report.json`,JSON.stringify(records,null,2));}finally{await browser.close();}
