import '@fontsource-variable/inter';
import './style.css';
import {Scene} from './scene.ts';
import {copy,type Key} from './i18n.ts';
import {DEFAULT,PRESETS,MAX_SAVES,STORAGE_KEY,EARTH_RADIUS,orbit,position,TAU,latitudeLimit,advance,explodeAt,parseArchive,encodeArchive,cleanName,nameKey,mergeMissions,type Archive,type Locale,type Mission} from './model.ts';
let locale:Locale=(['en','ru','kk'].includes(new URLSearchParams(location.search).get('lang')||'')?new URLSearchParams(location.search).get('lang'):'en') as Locale;
const t=(key:Key)=>copy[locale][key];
const $=<T extends HTMLElement=HTMLElement>(selector:string)=>document.querySelector<T>(selector)!;
const esc=(str:string)=>str.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const tx=(key:Key,tag='span',cls='')=>`<${tag} data-i18n="${key}" class="${cls}">${t(key)}</${tag}>`;
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
let archive:Archive={version:1,current:{...DEFAULT},missions:[]};let expectedRaw:string|null=null,unreadable=false,storageUnavailable=false,conflict=false;
try{expectedRaw=localStorage.getItem(STORAGE_KEY);if(expectedRaw)archive=parseArchive(expectedRaw);}catch{if(expectedRaw)unreadable=true;else storageUnavailable=true;}
let seconds=0,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,timeSpeed=60,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let progress=0,manual=false,chapter=-1,selected:number[]=[],importToken=0,modalToken=0,grouping='',lastStatus:Key|null=null;
const undoHistory:Archive[]=[];
const icon=(kind:'orbit'|'arrow'|'sat'|'plus')=>kind==='orbit'?'<svg viewBox="0 0 28 28" fill="none" aria-hidden="true"><circle cx="14" cy="14" r="5"/><ellipse cx="14" cy="14" rx="13" ry="6" transform="rotate(-35 14 14)"/><circle cx="23" cy="8" r="2" fill="currentColor" stroke="none"/></svg>':kind==='arrow'?'<span aria-hidden="true">↗</span>':kind==='plus'?'<span aria-hidden="true">＋</span>':'<span aria-hidden="true">◇</span>';
const help=(key:Key)=>`<details class="help"><summary aria-label="${esc(t(key))}" data-help="${key}">?</summary>${tx(key,'p')}</details>`;
$('#app').innerHTML=`
 <a class="skip" href="#mission">${t('skip')}</a>
 <header class="header wrap"><a class="brand" href="#top" aria-label="ORBIT">${icon('orbit')}<span>ORBIT</span></a><span class="brand-caption" data-i18n="lab">${t('lab')}</span><nav aria-label="Sections"><a href="#mission" data-i18n="navMission">${t('navMission')}</a><a href="#construction" data-i18n="navBuild">${t('navBuild')}</a><a href="#library" data-i18n="navLibrary">${t('navLibrary')}</a></nav><div class="languages" aria-label="Language">${(['en','ru','kk'] as Locale[]).map(l=>`<button data-lang="${l}" aria-pressed="${l===locale}">${l.toUpperCase()}</button>`).join('')}</div></header>
 <main id="top">
 <section class="intro wrap"><div>${tx('eyebrow','p','eyebrow')}${tx('title','h1')}</div><div class="intro-copy">${tx('intro','p','lead')}${tx('introNote','p','subtle')}<a class="text-link" href="#mission">${tx('navMission')}${icon('arrow')}</a></div><span class="intro-coordinate" aria-hidden="true">R + h / μ</span></section>
 <section id="mission" class="mission wrap" aria-labelledby="mission-heading"><h2 class="sr-only" id="mission-heading" data-i18n="current">${t('current')}</h2>
 <div class="workspace"><div class="viewport"><div class="scene-top"><div class="view-switch" role="group" aria-label="View"><button id="sat-tab" aria-pressed="true">${icon('sat')}${tx('satTab')}</button><button id="orbit-tab" aria-pressed="false">${icon('orbit')}${tx('orbitTab')}</button></div><span class="study-tag"><i></i> <span>ORBIT / 01</span></span></div>
 <div id="scene" class="scene" tabindex="0" role="group" aria-label="${esc(t('sceneLabel'))}"><div class="diagram" aria-hidden="true"></div></div>
 <div class="scene-bottom"><p id="scene-note" class="mono">${t('satNote')}</p><button id="reset-view" class="quiet">${tx('resetView')} <span aria-hidden="true">↺</span></button></div><p class="view-hint" data-i18n="viewHint">${t('viewHint')}</p>
 <div id="graphics-status" hidden><p></p><button id="retry" class="quiet" data-i18n="retry">${t('retry')}</button></div>
 <div class="timeline"><div class="time-head"><button id="play" class="icon-button"></button><div><span class="tiny" data-i18n="time">${t('time')}</span><output id="clock" class="mono">00:00:00</output></div><label for="speed" class="sr-only" data-i18n="speed">${t('speed')}</label><select id="speed"><option value="1">1×</option><option value="60" selected>60×</option><option value="300">300×</option></select><button id="restart" class="icon-button" aria-label="${esc(t('restart'))}">↺</button></div><label class="sr-only" for="phase" data-i18n="scrub">${t('scrub')}</label><input id="phase" type="range" min="0" max="360" step="1" value="0"><p class="tiny" data-i18n="motionNote">${t('motionNote')}</p></div>
 </div><aside class="config" aria-labelledby="config-heading"><div class="config-heading">${tx('config','h2')}<span class="mono" aria-hidden="true">01—03</span></div>
 <fieldset><legend data-i18n="presets">${t('presets')}</legend><div class="presets">${(['equatorial','explorer','polar'] as Key[]).map((key,i)=>`<button data-preset="${i}"><span class="preset-graphic p${i}" aria-hidden="true"></span>${tx(key)}<small>${PRESETS[i].altitude} km / ${PRESETS[i].inclination}°</small></button>`).join('')}</div>${tx('presetNote','p','tiny')}</fieldset>
 <div class="range-field"><div><label for="altitude" data-i18n="altitude">${t('altitude')}</label>${help('altitudeHelp')}<output id="altitude-out" for="altitude"></output></div><input id="altitude" type="range" min="250" max="2000" step="1"><div class="range-extremes mono"><span>250 km</span><span>2,000 km</span></div></div>
 <div class="range-field"><div><label for="inclination" data-i18n="inclination">${t('inclination')}</label>${help('inclinationHelp')}<output id="inclination-out" for="inclination"></output></div><input id="inclination" type="range" min="0" max="180" step="1"><div class="range-extremes mono"><span>0°</span><span>90°</span><span>180°</span></div></div>
 <fieldset><legend>${tx('payload')}${help('payloadHelp')}</legend><div class="options">${(['optical','relay'] as const).map(v=>`<button data-payload="${v}" aria-pressed="false">${tx(v)}</button>`).join('')}</div></fieldset>
 <fieldset><legend>${tx('blanket')}${help('blanketHelp')}</legend><div class="options">${(['gold','silver'] as const).map(v=>`<button data-blanket="${v}" aria-pressed="false"><span class="swatch ${v}" aria-hidden="true"></span>${tx(v)}</button>`).join('')}</div></fieldset>
 <button id="deploy" class="deploy"></button>${tx('panelsNote','p','tiny')}<button id="reset" class="text-link quiet">${tx('reset')} <span aria-hidden="true">↺</span></button>
 </aside></div>
 <div class="metrics"><div>${tx('period','p','tiny')}<p><output id="period"></output><span data-i18n="minutes">${t('minutes')}</span></p></div><div>${tx('velocity','p','tiny')}<p><output id="velocity"></output><span>km/s</span></p></div><div>${tx('latitude','p','tiny')}<p><output id="latitude"></output><span>°</span></p>${tx('latNote','p','metric-note')}</div><div>${tx('perDay','p','tiny')}<p><output id="revolutions"></output></p></div></div>
 </section>
 <section id="construction" class="construction"><div class="section-intro wrap">${tx('buildEyebrow','p','eyebrow')}<div>${tx('buildTitle','h2')}${tx('buildIntro','p','subtle')}</div></div><div id="scroll-study"><div class="assembly-sticky wrap"><div class="assembly-caption"><span id="chapter-number" class="mono">01 / 05</span><h3 id="chapter-title"></h3><p id="chapter-body"></p><div class="chapter-dots" role="group" aria-label="${t('step')}">${[0,1,2,3,4].map(i=>`<button data-chapter="${i}" aria-label="${esc(t(('chapter'+i) as Key))}">0${i+1}</button>`).join('')}</div></div><div id="assembly-scene" class="scene" tabindex="0" role="group" aria-label="${esc(t('sceneLabel'))}"><div class="diagram" aria-hidden="true"></div></div><div class="assembly-controls"><div class="assembly-mode"><button id="follow" aria-pressed="true">${tx('followScroll')}</button><span id="assembly-mode" class="tiny"></span></div><div class="assembly-slider"><label for="assembly" data-i18n="assembly">${t('assembly')}</label><input type="range" id="assembly" min="0" max="100" step="1" value="0"><output for="assembly" id="assembly-out" class="mono">0%</output></div><div class="assembly-extremes tiny">${tx('assembled')}${tx('separated')}</div></div></div></div></section>
 <section id="library" class="library wrap" aria-labelledby="library-title"><div class="library-heading"><div>${tx('libraryEyebrow','p','eyebrow')}<h2 id="library-title" data-i18n="libraryTitle">${t('libraryTitle')}</h2>${tx('libraryIntro','p','subtle')}</div><div class="transfer"><button id="export">${tx('export')} <span aria-hidden="true">↗</span></button><button id="import">${tx('import')} <span aria-hidden="true">↙</span></button><input id="import-file" type="file" accept="application/json,.json" hidden>${tx('localNote','p','tiny')}</div></div>
 <form id="save-form"><label for="mission-name" data-i18n="name">${t('name')}</label><div class="save-line"><input id="mission-name" name="name" maxlength="40" autocomplete="off" placeholder="${esc(t('placeholder'))}" required><button id="save" class="primary" type="submit">${icon('plus')}${tx('save')}</button><span id="save-count" class="mono">0 / 8</span></div></form>
 <div class="status-line"><p id="status" role="status" aria-live="polite"></p><button id="undo" disabled data-i18n="undo">${t('undo')}</button></div><div id="storage-warning" role="status" hidden><p></p><button id="download-raw" class="quiet" data-i18n="downloadRaw">${t('downloadRaw')}</button><button id="replace-storage" class="quiet" data-i18n="replaceStorage">${t('replaceStorage')}</button></div><div id="saved" aria-label="${t('missionList')}"></div><div id="comparison"></div>
 </section>
 <section id="model" class="learn wrap"><div>${tx('learnEyebrow','p','eyebrow')}${tx('learnTitle','h2')}</div><div>${tx('learnIntro','p','subtle')}<details id="equations"><summary data-i18n="formulas">${t('formulas')}</summary><div class="equations"><p><span data-i18n="radius">${t('radius')}</span><code>r = R + h</code></p><p><span data-i18n="velocity">${t('velocity')}</span><code>v = √(μ / r)</code></p><p><span data-i18n="period">${t('period')}</span><code>T = 2π √(r³ / μ)</code></p></div>${tx('equationNote','p','tiny')}${tx('constants','p','mono')}${tx('assumptions','p','subtle')}</details><p class="tiny sources-label" data-i18n="sources">${t('sources')}</p><div class="sources">${['https://pwg.gsfc.nasa.gov/stargaze/Skepl3rd.htm','https://ssd.jpl.nasa.gov/astro_par.html','https://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html','https://www.esa.int/Applications/Satellite_navigation/Galileo/Satellite_anatomy'].map((url,i)=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${tx(('source'+(i+1)) as Key)} ${icon('arrow')}</a>`).join('')}</div></div></section>
 </main><footer class="footer wrap"><a class="brand" href="#top">${icon('orbit')}ORBIT</a><div>${tx('footer','p')}${tx('footerNote','p','tiny')}</div><span class="mono">EXPERIMENT / 008</span></footer>
 <dialog id="dialog" aria-labelledby="dialog-title"><div class="dialog-inner"><h2 id="dialog-title"></h2><p id="dialog-body"></p><div id="dialog-content"></div><div id="dialog-actions"></div></div></dialog>`;

function status(key:Key){lastStatus=key;$('#status').textContent=t(key);}
function storageNotice(){const node=$('#storage-warning');node.hidden=!(unreadable||storageUnavailable||conflict);node.querySelector('p')!.textContent=conflict?t('storageChanged'):t(unreadable?'storageCorrupt':'storageBlocked');$('#replace-storage').hidden=!unreadable;$('#download-raw').hidden=!unreadable;}
function persist(){
 if(unreadable||conflict){storageNotice();return;}
 try{if(localStorage.getItem(STORAGE_KEY)!==expectedRaw){conflict=true;storageNotice();return;}const raw=encodeArchive(archive);localStorage.setItem(STORAGE_KEY,raw);expectedRaw=raw;storageUnavailable=false;}catch{storageUnavailable=true;}storageNotice();
}
function beforeChange(){undoHistory.push(clone(archive));if(undoHistory.length>40)undoHistory.shift();$('#undo').removeAttribute('disabled');}
function changed(){persist();sync();}
function mutate(action:()=>void){beforeChange();action();grouping='';changed();}
function modal(title:Key,body:Key,actions:{key:Key;run:()=>void;primary?:boolean}[],content:string='') {
 const dialog=$<HTMLDialogElement>('#dialog');modalToken++;const token=modalToken;if(dialog.open)dialog.close();$('#dialog-title').textContent=t(title);$('#dialog-body').textContent=t(body);$('#dialog-content').innerHTML=content;const holder=$('#dialog-actions');holder.replaceChildren();
 const cancel=document.createElement('button');cancel.textContent=t('cancel');cancel.onclick=()=>{if(token!==modalToken)return;modalToken++;dialog.close();};holder.append(cancel);
 for(const action of actions){const b=document.createElement('button');b.textContent=t(action.key);b.dataset.action=action.key;if(action.primary)b.className='primary';b.onclick=()=>{if(token!==modalToken)return;modalToken++;dialog.close();action.run();};holder.append(b);}
 dialog.showModal();cancel.focus();
}
$<HTMLDialogElement>('#dialog').addEventListener('cancel',()=>{modalToken++;});
function mini(mission:Mission) {
 const angle=mission.inclination>90?180-mission.inclination:mission.inclination;
 return `<svg class="mini" viewBox="0 0 120 90" fill="none" aria-hidden="true"><circle cx="60" cy="45" r="24" fill="#242631" stroke="#565869"/><ellipse cx="60" cy="45" rx="${(24+mission.altitude/100).toFixed(1)}" ry="10" transform="rotate(${-angle} 60 45)" stroke="#b4a1f6"/><path d="M36 45h48M60 21v48" stroke="#565869" stroke-dasharray="2 3"/></svg>`;
}
function renderSaved(){
 const node=$('#saved');$('#save-count').textContent=`${archive.missions.length} / ${MAX_SAVES}`;
 if(!archive.missions.length){node.innerHTML=`<div class="empty">${icon('orbit')}<div><h3>${t('empty')}</h3><p>${t('emptyBody')}</p></div><span class="mono" aria-hidden="true">— / 08</span></div>`;renderCompare();return;}
 node.innerHTML=archive.missions.map((m,i)=>`<article class="saved-mission">${mini(m.mission)}<div class="saved-details"><span class="tiny">${String(i+1).padStart(2,'0')} / ${t(m.mission.payload)}</span><h3>${esc(m.name)}</h3><p class="mono">${m.mission.altitude} km <span>/</span> ${m.mission.inclination}° <span>/</span> ${(orbit(m.mission.altitude).period/60).toFixed(1)} ${t('minutes')}</p></div><div class="saved-actions"><button data-load="${i}" aria-label="${esc(t('load')+' '+m.name)}">${t('load')}</button><button data-compare="${i}" aria-pressed="${selected.includes(i)}" aria-label="${esc(t('compare')+' '+m.name)}">${t('compare')}</button><button data-delete="${i}" class="quiet" aria-label="${esc(t('remove')+' '+m.name)}">×</button></div></article>`).join('');
 node.querySelectorAll<HTMLButtonElement>('[data-load]').forEach(b=>b.onclick=()=>{mutate(()=>{archive.current=clone(archive.missions[Number(b.dataset.load)].mission);seconds=0;});status('loaded');$('#mission').scrollIntoView({behavior:reduced?'instant':'smooth'});});
 node.querySelectorAll<HTMLButtonElement>('[data-compare]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.compare);selected=selected.includes(i)?selected.filter(n=>n!==i):[...selected.slice(-1),i];renderSaved();$<HTMLButtonElement>(`[data-compare="${i}"]`).focus({preventScroll:true});});
 node.querySelectorAll<HTMLButtonElement>('[data-delete]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.delete);modal('deleteTitle','deleteBody',[{key:'confirm',primary:true,run:()=>{mutate(()=>{archive.missions.splice(i,1);selected=[];});status('removed');$('#undo').focus({preventScroll:true});}}],`<p class="import-name">${esc(archive.missions[i].name)}</p>`);});renderCompare();
}
function renderCompare(){
 const node=$('#comparison');if(selected.length<2){node.innerHTML=`<p class="compare-hint">${t('compareHint')} <span class="mono">${selected.length} / 2</span></p>`;return;}
 const [a,b]=selected.map(i=>archive.missions[i]);if(!a||!b){selected=[];renderCompare();return;}
 const metrics=(m:Mission)=>[`${m.altitude} km`,`${m.inclination}°`,`${(orbit(m.altitude).period/60).toFixed(1)} ${t('minutes')}`,`${orbit(m.altitude).speed.toFixed(3)} km/s`,`±${latitudeLimit(m.inclination)}°`,t(m.payload),t(m.blanket),t(m.deployed?'deployedState':'stowedState')];
 const av=metrics(a.mission),bv=metrics(b.mission),keys:Key[]=['altitude','inclination','period','velocity','latitude','payload','blanket','solarWings'];
 node.innerHTML=`<div class="compare-heading"><h3>${t('compareTitle')}</h3><button id="clear-compare" class="quiet">${t('clearCompare')} ×</button></div><div class="table-scroll"><table><caption class="sr-only">${t('compareTitle')}</caption><thead><tr><th scope="col">${t('property')}</th><th scope="col">${esc(a.name)}</th><th scope="col">${esc(b.name)}</th></tr></thead><tbody>${keys.map((key,i)=>`<tr class="${av[i]!==bv[i]?'different':''}"><th scope="row">${t(key)} ${av[i]!==bv[i]?`<span class="sr-only">(${t('difference')})</span>`:''}</th><td>${av[i]}</td><td>${bv[i]}</td></tr>`).join('')}</tbody></table></div>`;
 $('#clear-compare').onclick=()=>{selected=[];renderSaved();};
}
function graphics(){if(!scene)return;const fallback=!scene.renderer||scene.lost;$('#scene').classList.toggle('no-webgl',fallback);$('#assembly-scene').classList.toggle('no-webgl',!assembly?.renderer||assembly.lost);$('#graphics-status').hidden=!fallback;$('#graphics-status p').textContent=t(scene.lost?'contextLost':'fallback');}
const scene=new Scene($('#scene')),assembly=new Scene($('#assembly-scene'),true);scene.changed=graphics;assembly.changed=graphics;
function diagram(mission:Mission,anatomy=false){
 const e=anatomy?progress:0,gap=e*45;
 if(!anatomy&&scene.mode==='orbit') {const p=position(mission.altitude,mission.inclination,seconds/orbit(mission.altitude).period*TAU);const r=orbit(mission.altitude).radius,scale=85/r;const points=Array.from({length:181},(_,j)=>{const q=position(mission.altitude,mission.inclination,j/180*TAU);return `${j?'L':'M'}${(180+q.x*scale).toFixed(2)},${(125-q.y*scale).toFixed(2)}`;}).join(' ');return `<svg viewBox="0 0 360 250"><circle cx="180" cy="125" r="${EARTH_RADIUS*scale}" fill="#292b39" stroke="#6e6d81"/><path d="M100 125h160" stroke="#aaa2bd" stroke-dasharray="4 4"/><path d="${points}" fill="none" stroke="#baacf3"/><circle cx="${180+p.x*scale}" cy="${125-p.y*scale}" r="4" fill="#e3dcff"/></svg>`;}
 return `<svg viewBox="0 0 360 280"><g transform="translate(180 140)"><path d="M-44 0h-75M44 0h75" stroke="#b8becb" stroke-width="5"/><g fill="#666eb1" stroke="#b9b8df" stroke-width="1">${[-1,1].map(side=>`<path d="M${side*(44+gap)} -28h${side*(mission.deployed?80:10)}v56h${-side*(mission.deployed?80:10)}z"/>`).join('')}</g><rect x="-34" y="${-40-gap}" width="68" height="14" fill="#bbc4cf"/><rect x="-32" y="-24" width="64" height="55" fill="${mission.blanket==='gold'?'#c5a471':'#a3abbc'}" stroke="#e6dfcd"/><rect x="-28" y="${36+gap}" width="56" height="18" fill="#777c8a"/><circle cx="0" cy="${-55-gap*1.4}" r="${mission.payload==='optical'?13:21}" fill="#303b54" stroke="#c3cad7" stroke-width="6"/></g></svg>`;
}
function syncChapter(){const next=Math.min(4,Math.floor(progress*4.99));if(next!==chapter){chapter=next;$('#chapter-number').textContent=`0${chapter+1} / 05`;$('#chapter-title').textContent=t(('chapter'+chapter) as Key);$('#chapter-body').textContent=t(('body'+chapter) as Key);document.querySelectorAll<HTMLButtonElement>('[data-chapter]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.chapter)===chapter)));}$('#assembly-out').textContent=`${Math.round(progress*100)}%`; $<HTMLInputElement>('#assembly').value=String(Math.round(progress*100));$('#follow').setAttribute('aria-pressed',String(!manual));$<HTMLButtonElement>('#follow').disabled=document.documentElement.classList.contains('text-enlarged')||document.documentElement.classList.contains('short-screen');$('#assembly-mode').textContent=manual?t('manual'):'';}
function sync(){
 const m=archive.current,o=orbit(m.altitude);$<HTMLInputElement>('#altitude').value=String(m.altitude);$<HTMLInputElement>('#inclination').value=String(m.inclination);$('#altitude-out').textContent=`${m.altitude.toLocaleString(locale)} km`;$('#inclination-out').textContent=`${m.inclination}°`;$('#period').textContent=(o.period/60).toLocaleString(locale,{minimumFractionDigits:1,maximumFractionDigits:1});$('#velocity').textContent=o.speed.toLocaleString(locale,{minimumFractionDigits:3,maximumFractionDigits:3});$('#latitude').textContent=`±${latitudeLimit(m.inclination)}`;$('#revolutions').textContent=o.revolutions.toLocaleString(locale,{minimumFractionDigits:2,maximumFractionDigits:2});
 document.querySelector<HTMLElement>('[data-i18n="motionNote"]')!.textContent=t('motionNote').replace('{speed}',String(timeSpeed));
 document.querySelectorAll<HTMLButtonElement>('[data-payload]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.payload===m.payload)));document.querySelectorAll<HTMLButtonElement>('[data-blanket]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.blanket===m.blanket)));document.querySelectorAll<HTMLButtonElement>('[data-preset]').forEach(b=>{const p=PRESETS[Number(b.dataset.preset)];b.setAttribute('aria-pressed',String(p.altitude===m.altitude&&p.inclination===m.inclination&&p.payload===m.payload&&p.blanket===m.blanket&&p.deployed===m.deployed));});
 $('#deploy').innerHTML=`<span aria-hidden="true">${m.deployed?'↔':'↗'}</span> ${t(m.deployed?'fold':'deploy')}`;$('#deploy').setAttribute('aria-pressed',String(m.deployed));$('#play').textContent=playing?'Ⅱ':'▶';$('#play').setAttribute('aria-label',t(playing?'pause':'play'));$('#play').setAttribute('aria-pressed',String(playing));$('#scene-note').textContent=t(scene.mode==='orbit'?'scaled':'satNote');scene.invalidate();assembly.invalidate();$('#scene .diagram').innerHTML=diagram(m);$('#assembly-scene .diagram').innerHTML=diagram(m,true);syncChapter();renderSaved();
}
function setLocale(next:Locale){locale=next;document.documentElement.lang=next;document.querySelectorAll<HTMLElement>('[data-i18n]').forEach(node=>node.textContent=t(node.dataset.i18n as Key));document.querySelectorAll<HTMLButtonElement>('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===next)));document.querySelectorAll<HTMLDetailsElement>('[data-help]').forEach(node=>node.setAttribute('aria-label',t(node.dataset.help as Key)));document.querySelectorAll<HTMLButtonElement>('[data-chapter]').forEach(b=>b.setAttribute('aria-label',t(('chapter'+b.dataset.chapter) as Key)));$<HTMLInputElement>('#mission-name').placeholder=t('placeholder');$('#restart').setAttribute('aria-label',t('restart'));$('#scene').setAttribute('aria-label',t(scene.mode==='orbit'?'orbitSceneLabel':'sceneLabel'));$('#assembly-scene').setAttribute('aria-label',t('sceneLabel'));$('#saved').setAttribute('aria-label',t('missionList'));if(lastStatus)status(lastStatus);chapter=-1;storageNotice();graphics();sync();}
document.querySelectorAll<HTMLButtonElement>('[data-lang]').forEach(b=>b.onclick=()=>setLocale(b.dataset.lang as Locale));
document.querySelectorAll<HTMLDetailsElement>('.help').forEach(details=>details.addEventListener('toggle',()=>{if(!details.open)return;const tip=details.querySelector<HTMLElement>('p')!;tip.style.left='-40px';tip.style.top='25px';const r=tip.getBoundingClientRect();if(r.right>innerWidth-16)tip.style.left=`${-40-(r.right-innerWidth+16)}px`;else if(r.left<16)tip.style.left=`${-40+16-r.left}px`;if(r.bottom>innerHeight-16)tip.style.top=`${-tip.offsetHeight-12}px`;}));
for(const field of ['altitude','inclination'] as const){const input=$<HTMLInputElement>('#'+field);input.addEventListener('input',()=>{if(grouping!==field){beforeChange();grouping=field;}archive.current[field]=Number(input.value);changed();});input.addEventListener('change',()=>grouping='');input.addEventListener('blur',()=>grouping='');}
document.querySelectorAll<HTMLButtonElement>('[data-preset]').forEach(b=>b.onclick=()=>mutate(()=>{archive.current=clone(PRESETS[Number(b.dataset.preset)]);seconds=0;}));
document.querySelectorAll<HTMLButtonElement>('[data-payload]').forEach(b=>b.onclick=()=>mutate(()=>{archive.current.payload=b.dataset.payload as Mission['payload'];}));
document.querySelectorAll<HTMLButtonElement>('[data-blanket]').forEach(b=>b.onclick=()=>mutate(()=>{archive.current.blanket=b.dataset.blanket as Mission['blanket'];}));
$('#deploy').onclick=()=>mutate(()=>{archive.current.deployed=!archive.current.deployed;});$('#reset').onclick=()=>{mutate(()=>{archive.current={...DEFAULT};seconds=0;});status('resetDone');};
$('#undo').onclick=()=>{const prev=undoHistory.pop();if(!prev)return;archive=prev;selected=[];grouping='';$('#undo').toggleAttribute('disabled',!undoHistory.length);changed();status('restored');};
$('#save-form').onsubmit=e=>{e.preventDefault();let name:string;try{name=cleanName($<HTMLInputElement>('#mission-name').value);}catch{status('nameInvalid');return;}const i=archive.missions.findIndex(m=>nameKey(m.name)===nameKey(name));const snapshot=clone(archive.current);const run=()=>{mutate(()=>{if(i>=0)archive.missions[i]={name,mission:snapshot};else archive.missions.push({name,mission:snapshot});});status('saved');};if(i>=0)modal('replaceTitle','replaceBody',[{key:'confirm',primary:true,run}],`<p class="import-name">${esc(name)}</p>`);else if(archive.missions.length>=MAX_SAVES)status('saveFull');else run();};
function download(raw:string,name:string){const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export').onclick=()=>{download(encodeArchive(archive),'orbit-missions.json');status('exportDone');};$('#import').onclick=()=>$<HTMLInputElement>('#import-file').click();
$<HTMLInputElement>('#import-file').onchange=async e=>{const input=e.target as HTMLInputElement,file=input.files?.[0],token=++importToken;input.value='';if(!file)return;if(file.size>100000){status('importLarge');return;}status('importBusy');try{const imported=parseArchive(await file.text());if(token!==importToken)return;modal('importTitle','importBody',[{key:'merge',run:()=>{let merged;try{merged=mergeMissions(archive.missions,imported.missions);}catch{status('mergeBad');return;}mutate(()=>{archive.missions=merged;selected=[];});status('importDone');}},{key:'replaceAll',primary:true,run:()=>{mutate(()=>{archive=clone(imported);selected=[];seconds=0;});status('importDone');}}],`<p class="mono">${imported.missions.length} ${t('importSummary')}</p><ul>${imported.missions.map(m=>`<li>${esc(m.name)}</li>`).join('')}</ul><p class="tiny">${t('mergeHint')}</p>`);}catch{if(token===importToken)status('importBad');}};
$('#replace-storage').onclick=()=>modal('storageReplaceTitle','storageReplaceBody',[{key:'confirm',primary:true,run:()=>{unreadable=false;persist();}}]);
$('#download-raw').onclick=()=>{if(expectedRaw)try{download(expectedRaw,'orbit-unreadable-backup.json');status('rawDone');}catch{status('rawFailed');}};
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY&&e.newValue!==expectedRaw){conflict=true;storageNotice();}});
$('#play').onclick=()=>{playing=!playing;sync();};$<HTMLSelectElement>('#speed').onchange=e=>{timeSpeed=Number((e.target as HTMLSelectElement).value);document.querySelector<HTMLElement>('[data-i18n="motionNote"]')!.textContent=t('motionNote').replace('{speed}',String(timeSpeed));};$('#restart').onclick=()=>{seconds=0;scene.invalidate();};
$<HTMLInputElement>('#phase').oninput=e=>{playing=false;seconds=Number((e.target as HTMLInputElement).value)/360*orbit(archive.current.altitude).period;sync();};
function view(mode:'satellite'|'orbit'){scene.mode=mode;$('#sat-tab').setAttribute('aria-pressed',String(mode==='satellite'));$('#orbit-tab').setAttribute('aria-pressed',String(mode==='orbit'));$('#scene').setAttribute('aria-label',t(mode==='orbit'?'orbitSceneLabel':'sceneLabel'));$('#scene').classList.toggle('orbit-view',mode==='orbit');sync();}
$('#sat-tab').onclick=()=>view('satellite');$('#orbit-tab').onclick=()=>view('orbit');$('#reset-view').onclick=()=>scene.resetView();$('#retry').onclick=()=>{scene.retry();assembly.retry();};
function scrollProgress(){const host=$('#scroll-study'),range=host.offsetHeight-window.innerHeight;return range>0?explodeAt((scrollY-(host.getBoundingClientRect().top+scrollY))/range):progress;}
function updateProgress(){if(!manual&&!document.documentElement.classList.contains('text-enlarged')&&!document.documentElement.classList.contains('short-screen'))progress=scrollProgress();syncChapter();assembly.invalidate();$('#assembly-scene .diagram').innerHTML=diagram(archive.current,true);}
$<HTMLInputElement>('#assembly').oninput=e=>{manual=true;progress=Number((e.target as HTMLInputElement).value)/100;updateProgress();};$('#follow').onclick=()=>{manual=false;updateProgress();};
document.querySelectorAll<HTMLButtonElement>('[data-chapter]').forEach(b=>b.onclick=()=>{manual=true;progress=Number(b.dataset.chapter)/4;updateProgress();});window.addEventListener('scroll',updateProgress,{passive:true});
const fontProbe=document.createElement('span');fontProbe.className='font-probe';fontProbe.textContent='M';document.body.append(fontProbe);new ResizeObserver(()=>{const enlarged=fontProbe.getBoundingClientRect().height>25;document.documentElement.classList.toggle('text-enlarged',enlarged);if(enlarged)manual=true;updateProgress();}).observe(fontProbe);
function layout(){const short=innerHeight<500&&innerWidth<650;document.documentElement.classList.toggle('short-screen',short);if(short)manual=true;updateProgress();}
window.addEventListener('resize',layout);matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{reduced=e.matches;if(reduced)playing=false;sync();});
let previous=performance.now(),lastClock=-1,frame=0;
function tick(now:number){const dt=Math.max(0,Math.min((now-previous)/1000,.1));previous=now;const active=!document.hidden&&scene.visible;seconds=advance(seconds,dt,timeSpeed,playing&&active);const phase=seconds/orbit(archive.current.altitude).period*TAU;
 if(active&&playing&&scene.mode==='orbit')scene.invalidate();scene.set(archive.current,phase,0,dt,reduced);assembly.set(archive.current,0,progress,dt,reduced);scene.render();assembly.render();
 const s=Math.floor(seconds);if(lastClock!==s){lastClock=s;$('#clock').textContent=`${Math.floor(s/3600).toString().padStart(2,'0')}:${Math.floor(s/60)%60<10?'0':''}${Math.floor(s/60)%60}:${(s%60).toString().padStart(2,'0')}`;if(document.activeElement!==$('#phase'))$<HTMLInputElement>('#phase').value=String(phase/TAU%1*360);if(!scene.renderer||scene.lost)$('#scene .diagram').innerHTML=diagram(archive.current);}
 frame=requestAnimationFrame(tick);
}
document.addEventListener('visibilitychange',()=>{previous=performance.now();});window.addEventListener('pagehide',()=>cancelAnimationFrame(frame));window.addEventListener('pageshow',e=>{if(e.persisted){previous=performance.now();frame=requestAnimationFrame(tick);}});
setLocale(locale);layout();storageNotice();requestAnimationFrame(tick);
// Read-only diagnostics for repeatable local browser verification.
Object.defineProperty(window,'__ORBIT',{value:{state:()=>({archive:clone(archive),locale,seconds,playing,timeSpeed,reduced,progress,manual,selected:[...selected],unreadable,storageUnavailable,conflict,scene:scene.state(),assembly:assembly.state(),scroll:{start:$('#scroll-study').getBoundingClientRect().top+scrollY,range:$('#scroll-study').offsetHeight-innerHeight}})}});
